#CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso pipeline
name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch
# gatilho de exec agendada = schedule
# gatilho de exec a partir de outro pipe = workflow_run
# types (tipos de evento): requested - aguardando na fila por uma máquina para ser executado /
#                           completed - depois de completo o primeiro workflow e
#                           in progress - executa enquanto o primeiro workflow ainda está rodando.

on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # condicional - if
    # `${ expressao}` ' '
    # == comparação
    # condicional nível de pipeline: antes dos 'steps'
    #comando para executar o workflow run se a execução de um outro workflow (que o disparou)
    #   tiver sido concluída com sucesso.

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    #passos do scripts de build
    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalacao do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalacao das dependências
      - name: Instalando dependências
        run: yarn

      # instalacao do Playwright
      - name: Instalando de Playwright
        run: yarn playwright install

      # instalacao os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      # Condicionais a nível de steps, se a pipeline até aqui não foi cancelada então rode este step
      # gera um arquivo de report no actions zipado para download
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} # execute este step de fazer upload dos artefatos exceto se ele for cancelado
        with:
          name: report
          path: ./playwright-report
